version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "testing"
    allow:
      - dependency-type: "direct"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
    # change after to main
    target-branch: "testing" # This routes the PRs directly to your testing branch. not the main which is default under security and quality
    allow:
      - dependency-type: "direct"
