version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/ERP"
    schedule:
      interval: "weekly"
    target-branch: "testing" # This routes the PRs directly to your testing branch. not the main which is default under security and quality
