services:
  api:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    restart: unless-stopped
    expose:
      - "8000"
    #env_file:
      # use the value of ENV_FILE if it is set and non-empty; otherwise use .env.production
    #  - .env.production
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      STRIPE_SUCCESS_URL: ${STRIPE_SUCCESS_URL}
      STRIPE_CANCEL_URL: ${STRIPE_CANCEL_URL}

    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
