services:

  db:
    image: mysql:8.0
    restart: "no"
    environment:
      MYSQL_DATABASE: erp_e2e
      MYSQL_USER: erp
      MYSQL_PASSWORD: erp
      MYSQL_ROOT_PASSWORD: root
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

  e2e-api:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    restart: "no"
    environment:
      FLASK_CONFIG: ${FLASK_CONFIG}
      DATABASE_URL: ${DATABASE_URL}
      STRIPE_SECRET_KEY:
      STRIPE_SUCCESS_URL: ${STRIPE_SUCCESS_URL}
      STRIPE_CANCEL_URL: ${STRIPE_CANCEL_URL}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    networks:
      default:
        aliases:
          - api
    depends_on:
     - db
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    restart: "no"
    ports:
      - "80:80"
    depends_on:
      - e2e-api

  e2e_playwright:
    build:
      context: .
      dockerfile: docker/Dockerfile.noble
    shm_size: 1gb
    restart: "no"
    environment:
      BASE_URL: http://nginx
      PLAYWRIGHT_JSON_OUTPUT_DIR: /app/frontend/test-results
    depends_on:
      - nginx
    volumes:
      - type: bind
        source: ./frontend/test-results
        target: /app/frontend/test-results
