"""update

Revision ID: 7bb36ed06613
Revises: d4c3b7079f2d
Create Date: 2026-08-24 01:35:27.278953

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "7bb36ed06613"
down_revision = "d4c3b7079f2d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("invoice_taxes", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("invoice_taxes_chk_1"), type_="check")
        batch_op.drop_constraint(batch_op.f("invoice_taxes_chk_2"), type_="check")
        batch_op.drop_constraint(batch_op.f("invoice_taxes_chk_3"), type_="check")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("invoice_taxes", schema=None) as batch_op:
        batch_op.create_check_constraint(
            batch_op.f("invoice_taxes_chk_3"),
            "((`tax_rate_percent` >= 0) and (`tax_rate_percent` <= 100))",
        )
        batch_op.create_check_constraint(
            batch_op.f("invoice_taxes_chk_2"), "(`tax_base` >= 0)"
        )
        batch_op.create_check_constraint(
            batch_op.f("invoice_taxes_chk_1"), "(`tax_amount` >= 0)"
        )

    # ### end Alembic commands ###
