# security headers
server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;

    # SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }
    # proxy
    # vite.config.js has a preview proxy but its handled here
    location /api/ {
        # docker internal dns resolver for api
        # if the container ir restarted/reloaded the IP addres will change. use it to avoid it
        resolver 127.0.0.11 valid=30s;
        # shared with e2e_api:8000 port besides production
        set $api_upstream api:8000;
        # proxy instruction
        # when browser requests GET /api/products nginx receives it nginx :80 and matches location /api/
        # nginx forward HTTP request to api:8000
        # http://api:8000
        proxy_pass http://$api_upstream;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
