"""update

Revision ID: 2ffaf005386e
Revises: c0e56a6469cb
Create Date: 2026-06-26 05:25:39.590807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ffaf005386e'
down_revision = 'c0e56a6469cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), server_default=sa.text('0.00'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('discount_percentage')

    # ### end Alembic commands ###
