"""update

Revision ID: c0e56a6469cb
Revises: 3f6df8af195b
Create Date: 2026-06-25 15:12:33.164510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0e56a6469cb'
down_revision = '3f6df8af195b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_id', sa.String(length=50), nullable=False))
        batch_op.drop_index(batch_op.f('ix_invoices_public_invoice_id'))
        batch_op.create_index(batch_op.f('ix_invoices_invoice_id'), ['invoice_id'], unique=True)
        batch_op.drop_column('public_invoice_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_invoice_id', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_id'))
        batch_op.create_index(batch_op.f('ix_invoices_public_invoice_id'), ['public_invoice_id'], unique=True)
        batch_op.drop_column('invoice_id')

    # ### end Alembic commands ###
