"""map

Revision ID: f2db6712ad3b
Revises: ea1f26f4ef2d
Create Date: 2026-06-23 14:20:54.369027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2db6712ad3b'
down_revision = 'ea1f26f4ef2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_products_product_category'))
        batch_op.drop_index(batch_op.f('ix_products_public_product_id'))
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_product_id'), ['product_id'], unique=True)
        batch_op.drop_column('product_description')
        batch_op.drop_column('product_category')
        batch_op.drop_column('public_product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_product_id', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('product_category', mysql.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('product_description', mysql.TEXT(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_products_product_id'))
        batch_op.drop_index(batch_op.f('ix_products_category'))
        batch_op.create_index(batch_op.f('ix_products_public_product_id'), ['public_product_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_product_category'), ['product_category'], unique=False)
        batch_op.drop_column('description')
        batch_op.drop_column('category')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
