"""update

Revision ID: ff7fb91ab3a5
Revises: 9f36ca86b2cb
Create Date: 2026-06-16 01:18:55.407032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff7fb91ab3a5'
down_revision = '9f36ca86b2cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('stripe_default_payment_method_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_default_payment_method_id', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
