name: Weekly and Dependabot Docker CI

on:
  schedule:
    - cron: "0 0 * * 1"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-build:
    name: Build Docker images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: ./docker/backend.Dockerfile
            image-name: backend
          - dockerfile: ./docker/frontend.Dockerfile
            image-name: frontend
          - dockerfile: ./docker/nginx.Dockerfile
            image-name: nginx

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          tags: ${{ matrix.image-name }}:latest
          push: false
