name: Weekly and Dependabot CI under Development Stage

on:
  schedule:
    - cron: '0 0 * * 1' 
  pull_request:
    branches:
      - testing
  workflow_dispatch: 

jobs:
  heavy-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - dockerfile: ./docker/backend.Dockerfile
            image-name: backend
          - dockerfile: ./docker/frontend.Dockerfile
            image-name: frontend
          - dockerfile: ./docker/nginx.Dockerfile
            image-name: nginx
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Docker image and push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          tags: ${{ matrix.image-name }}:latest
          # add docker/login-action and switch to true for the cloud environment
          push: false
